# Generated by Django 3.1.2 on 2022-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='RDKit_desc',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
