# Generated by Django 3.1.2 on 2022-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0002_molecule_rdkit_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='avfp',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
