# Generated by Django 3.1.2 on 2022-08-26 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0005_molecule_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='molecule',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
