# Generated by Django 3.1.2 on 2022-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0006_auto_20220826_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='gaussianPM7_desc',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
