# Generated by Django 3.1.2 on 2022-08-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptor', '0007_molecule_gaussianpm7_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='gaussianPM7_desc',
            new_name='PM7_desc',
        ),
    ]
